### ISSUE TITLE
统一文档风格

### ISSUE THREAD

**Issue by vizv** [LCTT/LFS-BOOK#1]
我们需要一个统一的文档风格，可以在这里发表你们的看法。

LeanCloud 的**[「文案风格指南」](http://open.leancloud.cn/copywriting-style-guide.html)**挺有指导意义的，大家可以看下，对其中不认同或者需要补充的作出表态。

文档风格的最终版本将写入协作规范，希望我们每个人在参与这个项目的人可以作出风格统一的翻译。

> 注意：对于想要加入 quip 的同学可以在此留下你的邮箱或者将邮箱发到 viz [at] linux.com

**Comment by vizv** [comment]
- 关于括号：对于非代码的内容请统一采用全角括号。
- 关于空格：参考 **[文案风格指南](http://open.leancloud.cn/copywriting-style-guide.html)**
  - 英文或数字与非标点的中文之间不需要空格，如：`LFS 当前主要支持 AMD/Intel 的 x86（32 位）和 x86_64（64 位）CPU`。
- 关于顿号 `、`：英文中没有顿号，根据语义（尤其是在列举时）将逗号改写成顿号，如 `例如：早先版本的 LFS、Ubuntu、Red Hat/Fedora、SuSE 或者是……`。

**Comment by vizv** [comment]
注意：尽量避免口语

**Comment by vizv** [comment]
注意：原 XML 文档中会包含换行符，当编译为 XHTML 时这些换行符会被浏览器解析成空格。所以在翻译时请避免在 XML 中插入换行符，这可能会导致浏览器在两个中文字符中间插入一个多余的空格。

**Comment by vizv** [comment]
大小单位 `GB` 应该翻译为 `GB` 而不是 `G`，因为 `G` 可以表示 `GB` 和 `GiB` 和 `Gb`，这些单位在 Linux 下表示的意义是不同的。

**Comment by vizv** [comment]
关于空格：为了美观，在数字和单位之间应加入一个空格，即使是英文字符做单位，比如应该写成 `5 GB` 而不是 `5GB`。

**Comment by vizv** [comment]
版本号应该反过来翻译以符合中文习惯：`Version 3.0` 应该翻译为 `3.0 版本`

**Comment by martin2011qi** [comment]
关于破折号的使用是“-”还是“——”

**Comment by vizv** [comment]
@martin2011qi TeX 的话是 `---`，这玩意我也不知道用哪个好，你试试看吧，看最后哪个看起来更好些……

**Comment by vizv** [comment]
Closed by #50
