### ISSUE TITLE
...貌似是一个错字，我不知道怎么处理，所以发到这里

### ISSUE THREAD

**Issue by ClearPlume** [LCTT/LFS-BOOK#101]
LFS8.2，路径是这个，LFS-BOOK/chapter06/glibc.xml ，第53行，内容如下：

> 首先船舰一个兼用的符号链接

“船舰”？我感觉应该是“创建”吧...

**Comment by vizv** [comment]
@martin2011qi 可以跟进下

**Comment by martin2011qi** [comment]
@ClearPlume  对应进去了，如果还有什么问题欢迎在这里反馈。

**Comment by hero616** [comment]
我怀疑这种地方用字或用词有些问题
序号，所在章节，怀疑有问题的句子
1、序章—前言，我开始意识到自己可以不必在受限于；不必再受
2、排版约定，部分的解释段落和会用它；
3、5.5.1，下面的指令将会修改 GCC 默认的动态链接器的位置，安装到 /tools 目录中的。
4、5.6.1，Linux 内核需要展示供系统 C 库（在 LFS 中是 Glibc）使用的应用程序编程接口（API）。；这里“展示”一次不好理解
5、5.2，都将围绕关汇编器和链接器实施多项特性测试
6、5.2、因为 Glibc 将一直使用传递给它配置脚本的
7、5.5.1、将每个解压软件包到 GCC 的目录下
8、6.3、本节不讨论也不安利任何特定的软件包管理器
9、6.3.2.3、通过自动创建这些可由用户自行创建的软链，

**Comment by martin2011qi** [comment]
> 我怀疑这种地方用字或用词有些问题
> 序号，所在章节，怀疑有问题的句子
> 1、序章—前言，我开始意识到自己可以不必在受限于；不必再受
> 2、排版约定，部分的解释段落和会用它；
> 3、5.5.1，下面的指令将会修改 GCC 默认的动态链接器的位置，安装到 /tools 目录中的。
> 4、5.6.1，Linux 内核需要展示供系统 C 库（在 LFS 中是 Glibc）使用的应用程序编程接口（API）。；这里“展示”一次不好理解
> 5、5.2，都将围绕关汇编器和链接器实施多项特性测试
> 6、5.2、因为 Glibc 将一直使用传递给它配置脚本的
> 7、5.5.1、将每个解压软件包到 GCC 的目录下
> 8、6.3、本节不讨论也不安利任何特定的软件包管理器
> 9、6.3.2.3、通过自动创建这些可由用户自行创建的软链，

详见PR #121。在关闭的 issues 下发问题，请把 issues 重开，不然很难找。
