### ISSUE TITLE
编译软件包10G内存不够用

### ISSUE THREAD

**Issue by ghost** [LCTT/LFS-BOOK#134]
![image](https://user-images.githubusercontent.com/62370031/78559059-4cd08800-7846-11ea-9f44-b5ec3569ee4a.png)
![image](https://user-images.githubusercontent.com/62370031/78559111-62de4880-7846-11ea-9faa-29e4a8c18193.png)

**Comment by martin2011qi** [comment]
10G是肯定够的，只要你构建完一个软件包删一个软件包(指解压出来的目录)。一般来说瓶颈在第六章Glibc，那里产生的中间文件是最多的。

**Comment by ghost** [comment]
您是说编译好的源代码可以删除，下一次编译的时候再解压吗？

**Comment by martin2011qi** [comment]
对，参考`5.3. 通用编译指南`的最后一个 note
