### ISSUE TITLE
测试编译bison错误

### ISSUE THREAD

**Issue by ghost** [LCTT/LFS-BOOK#135]
![image](https://user-images.githubusercontent.com/62370031/79031953-468b3480-7bd5-11ea-919b-9e98767a80fc.png)

**Comment by ghost** [comment]
还有
![image](https://user-images.githubusercontent.com/62370031/79035517-fe2e3f80-7bf1-11ea-8f5b-d111f77a4329.png)

**Comment by Ipfirn** [comment]
还有
![image](https://user-images.githubusercontent.com/62370031/79036166-1c973980-7bf8-11ea-9f53-434a48b11232.png)

**Comment by ghost** [comment]
还有
![image](https://user-images.githubusercontent.com/62370031/79036169-2e78dc80-7bf8-11ea-83c1-d7af0e379f65.png)

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/62370031/79041492-ec18c500-7c22-11ea-9bde-e5323988246a.png)

**Comment by martin2011qi** [comment]
没看懂？Bison要在安装完Flex后测试。后面的也是测试的问题？

**Comment by ghost** [comment]
是的

**Comment by ghost** [comment]
bison是在构建临时工具时检查错误的，gawk也一样，glibc是在安装最后系统软件时检查错误的

**Comment by martin2011qi** [comment]
第五章的 bison 没有必要做测试。出错是很正常的。
gawk 也是第五章吗？那就也没有必要测试。
参考第四章有测试观点。一般第五章不是强制要求不测试。第六章强制要求以外看心情测试。
glibc 是第六章？以前好像见过，你每次解压的软件包都删除了吗？特别是 Binutils 和 GCC，每一遍都要删除上一次的重新解压。第五章构建 Libstdc++ 的 GCC 也是。而且要保证 dummy.c 相关的测试输出结果都是一样的。

**Comment by ghost** [comment]
是的

**Comment by ghost** [comment]
每一次我都会检查有没有删除，每一次的dummy.c都是一样的结果

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/62370031/79299016-7314b880-7f15-11ea-9ce9-9e2360501abc.png)

**Comment by Ipfirn** [comment]
![image](https://user-images.githubusercontent.com/62370031/79301657-b58dc380-7f1c-11ea-9eb4-4df02a21cadb.png)
我还没有设置root密码呢

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/62370031/79310746-01e1ff00-7f2f-11ea-9e72-530e75588dfa.png)
这次我编译inetutils出现了错误

**Comment by martin2011qi** [comment]
ptys耗尽是常见问题，第四章测试观点中提到了吧？
http://www.linuxfromscratch.org/lfs/faq.html#no-ptys

中间那个？

Inetutils你装的哪个版本？1.9.4 也有这个问题？
试试看在 configure 前运行下面的命令，前几版倒是这样的。
echo '#define PATH_PROCNET_DEV "/proc/net/dev"' >> ifconfig/system/linux.h

**Comment by ghost** [comment]
该解决方案可能需要重新编译您的内核。首先，转到内核的源目录，然后查看.config文件。如果没有.config文件，并且您正在运行随rpm，aptget或发行版使用的任何版本一起安装的预编译内核，则需要从发行版的支持常见问题解答，邮件列表或IRC渠道中寻求支持。  
什么意思

**Comment by ghost** [comment]
为什么expect -c "spawn ls"会有两种不同的输出

**Comment by Ipfirn** [comment]
![image](https://user-images.githubusercontent.com/62370031/79420057-ac6b2800-7fea-11ea-99e9-ac75ed475b84.png)

**Comment by Ipfirn** [comment]
![image](https://user-images.githubusercontent.com/62370031/79530702-acc6fa00-80a2-11ea-8dd4-18dc797c3cc1.png)

**Comment by Ipfirn** [comment]
![image](https://user-images.githubusercontent.com/62370031/79531691-b0a84b80-80a5-11ea-8d51-b482510bc96b.png)

**Comment by ghost** [comment]
根据以上输出，我们再次修改 /etc/locale.conf，将字符映射表设置为标准形式（「zh_CN.utf8」变为「zh_CN.UTF-8」）。同理，也可一并查询以下设置的标准命令，然后将其添加到 bash 的启动文件中 （译者注：对于 bash 来说，启动文件为 .bashrc）。
以上的命令将会打印当前区域设置的语言、字符编码、本地货币单位以及电话国际编码。如果出现类似下文的错误输出，可能是你没有严格按照第六章指导的方法操作或者是你当前所用的 Glibc 不支持。
你到底要写入.bashrc还是直接打在终端？？？
