### ISSUE TITLE
请教一下这句话

### ISSUE THREAD

**Issue by martin2011qi** [LCTT/LFS-BOOK#15]
原先的翻译和我重新整理的八九不离十，但是句子太长短句非常不舒服，大家有什么好的建议吗？

原文：The <command>exec env -i.../bin/bash</command> command in the <filename>.bash_profile</filename> file replaces the running shell with a new one with a completely empty environment, except for the <envar>HOME</envar>, <envar>TERM</envar>, and <envar>PS1</envar> variables.

译文：<filename>.bash_profile</filename>中的命令<command>exec env -i.../bin/bash</command>用一个除了 <envar>HOME</envar>，<envar>TERM</envar>和<envar>PS1</envar>变量外环境完全为空的 shell 代替运行中的 shell。

**Comment by dongfengweixiao** [comment]
好长好长的句子。。。

译文：.bash_profile 中的命令 exec env -i.../bin/bash 将会使用一个新的 shell 来代替运行中的 shell，
且这个新的 shell 中除 HOME，TERM 和 PS1 外的环境变量都为空。

**Comment by martin2011qi** [comment]
恩好
