### ISSUE TITLE
翻译的LFS-BOOK-7.7-systemd有个标点符号错误

### ISSUE THREAD

**Issue by hellozjf** [LCTT/LFS-BOOK#38]
[https://linux.cn/lfs/LFS-BOOK-7.7-systemd/chapter06/kbd.html](https://linux.cn/lfs/LFS-BOOK-7.7-systemd/chapter06/kbd.html)，这页中`sed -i 's/\（RESIZECONS_PROGS=\）yes/\1no/g' configure`用了中文的括号，请纠正这个问题

还有6.63. Systemd-219章节里面`sed -i "s:blkid/::" $（grep -rl "blkid/blkid.h"）`也用了中文的括号，请纠正

**Comment by wxy** [comment]
谢谢，GITHUB 里面已经修正了，就是网页那边没更新，我马上更新。谢谢。
