### ISSUE TITLE
8.0rc1 需要翻译对应的文件列表

### ISSUE THREAD

**Issue by martin2011qi** [LCTT/LFS-BOOK#44]
第一弹：章节 1-4 & 7-9

以下需要重新翻译
chapter01/changelog.xml（改得太多）
chapter02/stages.xml（新章节）

以下需要部分翻译
chapter01/aboutlfs.xml
chapter02/creatingpartition.xml
chapter02/introduction.xml
chapter03\packages.xml
chapter05\gcc-pass1.xml
chapter05\gcc-pass2.xml
chapter05\tcl.xml
chapter05\texinfo.xml
chapter05\toolchaintechnotes.xml
chapter07\udev.xml
chapter07\symlinks.xml （大段追加）
chapter07\systemd-custom.xml（大段追加）
chapter08\kernel.xml
chapter08\grub.xml
chapter09\teend.xml

**Comment by vizv** [comment]
这个也尽量整理到 `README.md` 的 TODO Section 中，这样大家都能看到。
