### ISSUE TITLE
翻译中的一些注意事项

### ISSUE THREAD

**Issue by martin2011qi** [LCTT/LFS-BOOK#45]
文档风格
1. 开始之前请务必先了解[统一文档风格](https://github.com/LCTT/LFS-BOOK/issues/1)，以便形成统一的文档风格。
2. 补充 <para> 中的内容，英文内容是会换行的。换行符最终会转换成空格，所以最好不要使用换行符，让 <para> 内容保持在同一行内。（如果原先翻译的内容有不在一行内的情况，且标点符号位于行末，暂时可以不用管。标点符号后加空格虽然不是很好，但可以勉强接受。）

翻译内容
1. <title> 和 <para> 中的内容要翻译，<screen> 中的内容不要翻译，也不要修改。特殊情况，小组讨论决定。

关于译注
1. 译者注的使用，7.7 中有比较多的译者注，其中有些非常棒，但有些其实可以通过翻译达到同样的效果。所以不是很建议加译者注，特别是需要修改原文格式的时候。

遇到问题怎么办？
1. QQ，Mail，Issue 合作翻译，不要有太大的负担，有不明白的就问出来。

**Comment by vizv** [comment]
应该写入 `CONTRIBUTING.md`，这样在提交 PR 之前会提示参考协作规范，你有空的话开个 PR 更新下 `CONTRIBUTING.md` 吧，可以在 `README.md` 中用大号粗体标注下要先阅读协作规范。

开 issue 不会有 reversion 记录，你 edit 过了以后不会看到你修改了什么……
