### ISSUE TITLE
Udev 中 u 的大小写问题

### ISSUE THREAD

**Issue by martin2011qi** [LCTT/LFS-BOOK#65]
问题来自 PR #57。感谢问题报告者 @Athenacle ，以及 @wxy 和 @vizv 的回答。
问题内容：关于原文中的 Udev。udev 本身就是一个专有名词了，没有必要首字母大写。
结论： udev 中的 u 确实没有专门大写的必要。
处置： 将文中非句首的 Udev 改为 udev。并将需要修改的地方报告给 LFS 英文项目维护团队。
状态：未对应

**Comment by Athenacle** [comment]
不仅仅是Udev的问题，后面还有一些写的是Systemd。其他的暂时还没发现

**Comment by vizv** [comment]
@Athenacle 对的，systemd 也是全小写……

**Comment by martin2011qi** [comment]
@Athenacle , @vizv 我知道了，一起改。

**Comment by vizv** [comment]
@martin2011qi 我查了原文，的确用的大写。不过我觉得应该用小写，所以你给上游报告下吧。至于翻译里到底用大写还是小写，我倾向于用小写，你自己做决定吧 :3

**Comment by martin2011qi** [comment]
@Athenacle @vizv @wxy 放在句首要首字母大写吗？

**Comment by Athenacle** [comment]
不用
你可以man 7 udev看看

**Comment by vizv** [comment]
@martin2011qi 不用
